name: CD

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Initialize Terraform
        run: terraform -chdir=prod init

      - name: Validate Terraform
        run: terraform -chdir=prod validate

      - name: Plan Terraform
        run: terraform -chdir=prod plan -out=tfplan

      - name: Apply Terraform
        run: terraform -chdir=prod apply -auto-approve tfplan
